version: "3.8"
services:
    front:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./front:/front
        working_dir: /front
        command: node
        tty: true
        ports:
            - 8080:8080
